name: TaskMaster - Collaborative Task Management
version: "2.0.0"
slug: taskmaster
description: A complete task management system with multi-user collaboration, date/time tracking, image uploads, and Home Assistant automation integration
url: https://github.com/yourusername/taskmaster-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
image: ghcr.io/home-assistant/{arch}-addon-taskmaster
