#!/bin/bash
# TaskMaster Installation Script for Home Assistant

echo "======================================"
echo "TaskMaster Add-on Installation Guide"
echo "======================================"
echo ""
echo "To install TaskMaster in Home Assistant:"
echo ""
echo "1. Copy the 'taskmaster-addon' folder to your Home Assistant add-ons directory:"
echo "   - If using Home Assistant OS: /addons/taskmaster-addon/"
echo "   - If using Docker: Copy to your add-ons volume"
echo "   - If using Supervised: /usr/share/hassio/addons/local/taskmaster-addon/"
echo ""
echo "2. Restart Home Assistant (if needed)"
echo ""
echo "3. Go to: Settings → Add-ons → Add-on Store"
echo ""
echo "4. Click the menu (⋮) and select 'Check for updates' or 'Reload'"
echo ""
echo "5. You should see 'TaskMaster' in the Local Add-ons section"
echo ""
echo "6. Click on it and press 'Install'"
echo ""
echo "7. After installation completes, click 'Start'"
echo ""
echo "8. Access the web interface at: http://homeassistant.local:8099"
echo ""
echo "======================================"
echo "Quick Start:"
echo "======================================"
echo ""
echo "1. Create a user (+ User button)"
echo "2. Select that user from the dropdown"
echo "3. Create a project (+ Project button)"
echo "4. Click the project to open it"
echo "5. Add tasks and start collaborating!"
echo ""
echo "For Home Assistant integration, see HOMEASSISTANT_CONFIG.yaml"
echo "For full documentation, see README.md"
echo ""
